# Lab 6: Machine Learning Pipeline

1. Read
2. Split
3. Divide
4. Train
5. Predict
6. Evaluate

---


**Course Code:** CS4082 Machine Learning

**Institution:** Effat University, Computer Science Department

**Student Name:** Ghala Alghamdi

**Student ID:** S23108212

**Instructor:** Dr. Naila Marir

**Date:** April 1, 2026


---

## ML Pipeline for Linear Regression

In [1]:
import numpy as np
import pandas as pd

data = {
    "area":[100, 150, 200, 250, 300],
    "bedrooms":[2, 3, 3, 4, 5],
    "age":[20, 15, 10, 5, 2],
    "price":[200, 300, 400, 500, 650]
}

df = pd.DataFrame(data)
df.to_csv("housing.csv", index=False)

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

### Step 1: Read

In [3]:
df = pd.read_csv("housing.csv")
df.head()

   area  bedrooms  age  price
0   100         2   20    200
1   150         3   15    300
2   200         3   10    400
3   250         4    5    500
4   300         5    2    650

### Step 2: Separate Features and the Label

In [4]:
X = df[["area", "bedrooms", "age"]]
y = df["price"]

### Step 3: Split the Data

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Step 4: Train Model

#### Step 4.1: Create Model

In [6]:
model = LinearRegression()

#### Step 4.2: Fit Model

In [7]:
model.fit(x_train, y_train)

LinearRegression()

### Step 5: Predict

In [8]:
y_pred = model.predict(x_test)

### Step 6: Evaluate

In [9]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE: ", rmse)

mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mse)

r2 = r2_score(y_test, y_pred)
print("R2: ", r2)

RMSE:  2.2737367544323206e-13
MSE:  5.169878828456423e-26
R2:  nan

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

## ML Pipeline for Linear Classification

In [10]:
import numpy as np
import pandas as pd

data = {
    "hours_studied":[2, 3, 4, 5, 6, 7, 8, 9],
    "attendance":[50, 60, 70, 80, 85, 90, 95, 100],
    "passed":[0, 0, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)
df.to_csv("students.csv", index=False)

In [11]:
from sklearn.linear_model import LogisticRegression

### Step 1: Read

In [12]:
df = pd.read_csv("students.csv")
df.head()

   hours_studied  attendance  passed
0              2          50       0
1              3          60       0
2              4          70       0
3              5          80       1
4              6          85       1

### Step 2: Separate Features and the Label

In [13]:
X = df[["hours_studied", "attendance"]]
y = df["passed"]

### Step 3: Split the Data

In [14]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Step 4: Train Model

#### Step 4.1: Create Model

In [15]:
model = LogisticRegression()

#### Step 4.2: Fit Model

In [16]:
model.fit(x_train, y_train)

LogisticRegression()

### Step 5: Predict

In [17]:
y_pred = model.predict(x_test)

### Step 6: Evaluate

In [18]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1_score)

Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0